INHERIT: config/nav.yml

site_name: "Docker Documentation"
site_author: "Docker"
site_url: "https://crazymax.dev/docker-docs/"
edit_uri: "edit/master/docs/"
copyright: "Copyright &copy; 2013-2021 Docker Inc. All rights reserved."
docs_dir: "docs"

repo_name: "crazy-max/docker-docs"
repo_url: "https://github.com/docker/docker.github.io"

theme:
  name: material
  custom_dir: overrides
  language: en
  include_search_page: false
  search_index_only: true
  features:
    - content.code.annotate
    - content.tabs.link
    #- navigation.expand
    - navigation.indexes
    #- navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/docs.svg
  favicon: assets/favicon.ico

extra:
  # FIXME: Google Analytics?
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  seo:
    # FIXME: Add Google and Bing site verification
    google: !ENV GOOGLE_SEARCH_KEY
    bing: !ENV BING_SEARCH_KEY
    #alexa:
    #yandex:
  social:
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/docker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Docker

extra_javascript:
  - assets/javascript/extra.js
extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/override.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  awesome-pages: {}
  git-revision-date-localized:
    type: iso_datetime
    fallback_to_build_date: true
  macros:
    include_dir: includes
  minify:
    minify_html: true
  search:
    prebuild_index: python
    lang:
      - en
