INHERIT: redirects.yml

nav:
  - Home: index.md
  - Guides:
    - Docker overview: guides/docker-overview.md
    - Get Docker: guides/get-docker.md
    - Get Started:
      - "Part 1: Getting started": guides/part1-getting-started.md
      - "Part 2: Sample application": guides/part2-sample-application.md
      - "Part 3: Update the application": guides/part3-update-the-application.md
      - "Part 4: Share the application": guides/part4-share-the-application.md
      - "Part 5: Persist the DB": guides/part5-persist-the-db.md
      - "Part 6: Use bind mounts": guides/part6-use-bind-mounts.md
      - "Part 7: Multi container apps": guides/part7-multi-container-apps.md
      - "Part 8: Using compose": guides/part8-using-compose.md
      - "Part 9: Image-building best practices": guides/part9-image-building-best-practices.md
      - "Part 10: What next?": guides/part10-what-next.md
  - Manuals:
    - Docker Desktop:
        - Overview: manuals/desktop/overview.md
  - Reference:
    - Reference documentation: reference/index.md
  - Articles: https://www.docker.com/blog/
