plugins:
  redirects:
    redirect_maps:
      engine/docker-overview.md: get-started/docker-overview.md
      engine/introduction/understanding-docker.md: get-started/docker-overview.md
      engine/understanding-docker.md: get-started/docker-overview.md
      engine/userguide/basics.md: get-started/docker-overview.md
      get-started/index.md: get-started/docker-overview.md
      introduction/understanding-docker.md: get-started/docker-overview.md
